# PostgreSQL. Versions 8.2 and up are supported.
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: doorkeeper_crawlers_development
  #username: doorkeeper_crawlers
  #password:
  #host: localhost
  #port: 5432
  #schema_search_path: myapp,sharedapp,public
  #min_messages: notice

test:
  <<: *default
  database: doorkeeper_crawlers_test

production:
  <<: *default
  database: doorkeeper_crawlers_production
  username: doorkeeper_crawlers
  password: <%= ENV['DOORKEEPER_CRAWLERS_PASSWORD'] %>
